export enum PermissionEnum {
  READ_USERS = "READ_USERS",
  WRITE_USERS = "WRITE_USERS",
  DELETE_USERS = "DELETE_USERS",
  MANAGE_ROLES = "MANAGE_ROLES",
  VIEW_DASHBOARD = "VIEW_DASHBOARD",
  EDIT_PROFILE = "EDIT_PROFILE"
}